_base_ = './default.py'

# Plane variant of basketball.py — swap hash=False, keep the same long-sequence training setup.

ModelParams = dict(
    base_path="/data2/dataset/longvideos/globalTasks/dataset_process/dense2sample2merge/points/resAlist_aux/1400_points_enhanced.ply",
    time_window_size=5,
    frame_interval=1,
    downsample=2.0,
    llffhold=10,
)

OptimizationParams = dict(
    dataloader=True,
    zerostamp_init=True,
    iterations=100_000,
    hash=False,
    levels=13,
    level_0_dim=32,
    hashmap_size=16,
    hash_init_lr=0.0002,
    hash_final_lr=0.000002,
    activation="ReLU",
    n_levels=16,
    n_features_per_level=8,
    base_resolution=16,
    n_neurons=128,
    open_clear_storage_hash=True,
    open_split_dy_lr=False,
    hash_batch_size=1024 * 256,
    max_lr_iteration=200_000,
    auto_encoder_levels=True,
    encoder_balanced_accumulation=True,
    gradient_accumulation_steps=8,
    gradient_clip_norm=10.0,
    lr_warmup_updates=1000,
    lr_warmup_start_factor=0.1,

    use_hashgrid=False,
    open_feat_cat=True,

    open_anchor_feat_delay=True,
    enable_lifetime_decay=False,
    lifetime_min_decay=0.5,
    mlp_chunk_size=0,
    primitive_type="3dgs",
    near_plane=0.01,
    absgrad=False,
    dy_lr_scale=1.0,
    clip_size=20,
    render_feature="all",
    render_kind="smooth",
    virtual_frame_interval=40,
    save_optimizer=True,
    skip_blender=True,
    blender_path="/data2/liangjie/dynamic/longvideo_learning_delay/data_process/",
    open_single_view=False,
    single_view_idx=730,
    blender_offset=0,
    blender_name="main",
    open_sync_time=False,

    opacity_factor=2,
    cov_factor=2,
    color_factor=2,
    offset_factor=4,
    # not using densification, set it to a large value
    start_stat=150000000,
    update_from=1600,
    update_interval=100,
    update_until=30000,
    success_threshold=0.8,
    densify_grad_threshold=0.0006,
    percentile=100,

    position_lr_max_steps=200_000,
    offset_lr_max_steps=200_000,
    mlp_opacity_lr_max_steps=200_000,
    mlp_cov_lr_max_steps=200_000,
    mlp_offset_lr_max_steps=200_000,
    mlp_color_lr_max_steps=200_000,
    mlp_featurebank_lr_max_steps=200_000,
    appearance_lr_max_steps=200_000,
)
